#root@node01:/home/ubuntu# cat /etc/ceph/ceph.conf
[global]
fsid = 8be96b85-e67a-49d8-bb15-6165b9ada7df

public network = 192.168.11.0/24
cluster network = 10.0.0.0/24

mon initial members = node01, node02, node03
mon host = 192.168.11.10, 192.168.11.11, 192.168.11.12

osd pool default crush rule = -1
mon allow pool delete = true

[mon.node01]
host = node01
mon addr = 192.168.11.10

[mon.node02]
host = node02
mon addr = 192.168.11.11

[mon.node03]
host = node03
mon addr = 192.168.11.12

[client.rgw.rgw01]
host = rgw01
rgw_frontends = "civetweb port=192.168.11.60:8080"

[client.rgw.node01]
host = node01
rgw_frontends = "civetweb port=192.168.11.10:8080"